"use client";
import { Nunito } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Header from "@/components/Header";
import useForecastStore from "../../store";
import { fetchForecast, fetchWeather } from "../../api/weather";
import { useEffect } from "react";
import Head from "next/head";

const nunito = Nunito({ subsets: ["latin"] });

/*  export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};  */

export default function RootLayout({ children }) {
  const setForecast = useForecastStore((state) => state.setForecast);
  const setWeather = useForecastStore((state) => state.setWeather);
  const setLoading = useForecastStore((state) => state.setLoading);

  const loadData = async () => {
    try {
      const foreData = await fetchForecast("istanbul");
      const weatData = await fetchWeather("istanbul");
      setForecast(foreData);
      setWeather(weatData);
      setLoading(false);
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <body className={nunito.className}>
        <Header />

        {children}
      </body>
    </html>
  );
}
